#+startup: overview
#+hugo_base_dir: ../
#+hugo_section: ./
* DONE À propos de moi
CLOSED: [2024-01-12 Fri 16:06]
:PROPERTIES:
:EXPORT_FILE_NAME: about
:EXPORT_HUGO_PAIRED_SHORTCODES:  icon
:EXPORT_OPTIONS: toc:nil
:END:


Toutes mes salutations les plus sincères. 
Je m'appelle Kevin, et j'aime apprendre et expérimenter de nouvelles choses chaque jour. Mes principaux centres d'intérêt sont la cuisine, un peu de bricolage, me balader et explorer de nouveaux coins à vélo.

Je traiterai de manière irrégulière de pas mal de sujets en espérant vous apprendre quelque chose (liste non exhaustive) : 
- Cuisine
- Vie quotidienne
- Informatique

Bonne lecture ! 
* Mentions légales
:PROPERTIES:
:EXPORT_FILE_NAME: mentions-legales
:EXPORT_HUGO_PAIRED_SHORTCODES:  icon
:EXPORT_OPTIONS: toc:nil
:END:

** Mentions légales

En vigueur au 18/03/2026

Conformément aux dispositions de la loi n°2004-575 du 21 juin 2004 pour la Confiance en l’économie
numérique, sont portées à la connaissance des internautes du site https://ckevin.fr, les présentes mentions légales. La connexion et la navigation sur ce site par les internautes implique approbation sans discussion ni réserve des mentions légales ci-dessous.


** Publication
M. Kevin C., contactable au courriel ci-contre blog@ckevin.fr dirige l'édition et la publication du blog *C. Kevin*, d'adresse https:/ckevin.fr. 

** Hébergement du site
Le site est hébergé sur les serveurs de la société Github, dont le siège social est situé au : 

88 Colin P. Kelly Junior Street 
San Francisco, California, United States.

** Utilisation du site.
Le blog *C. Kevin* est normalement accessible, à tout moment, gratuitement et sans contrepartie, à tout utilisateur. Toutefois, Kevin C. pourra à tout moment et de manière unilatérale, restreindre ou suspendre l'accès au blog *C. Kevin* afin de mettre en ligne des ajouts ou modification de contenu. Kevin C. ne pourra en aucun cas être tenu responsable des conséquences éventuelles de cette indisponibilité sur les activités des internautes, ni de toute erreur ou omission qui pourrait être constatée sur le site.
Par ailleurs, toute utilisation, reproduction, diffusion, commercialisation, modification de toute ou partie du blog *C. Kevin*, sans crédit du blog est strictement interdite et pourra entraîner des actions et poursuites judiciaires telles que prévues par la règlementation en vigueur présentée dans les articles L.335-2 et suivants du Code de la propriété intellectuelle.


** Cookies 
Le blog *C. Kevin* est susceptible d'installer automatiquement sur le disque dur de votre appareil lors de votre visite sur le blog un ou plusieurs cookies, provenant des éventuels partenaires du blog ou du système de statistiques de visites ou tout autre service proposé par le blog. Il est possible de supprimer les cookies installés lors de la visite sur le blog *C. Kevin* en parcourant les paramètres de votre navigateur pour supprimer vos données de navigation. Elle devra intervenir après la fin de votre visite sur le site, afin de ne pas perturber la navigation sur le blog *C. Kevin*. 

** Crédits et copyright photos
Ne sont utilisées sur le blog *C. Kevin* que des photos prises par Kevin C, ou à défaut d'un tiers crédité dans la légende de la photo avec son accord, ou bien d'une banque d'images également créditée proposant des illustrations libres de droit pouvant prendre la forme de diverses licences. 
* Index
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_PAIRED_SHORTCODES:  icon
:EXPORT_OPTIONS: toc:nil
:END:


** C. Kevin le blog
Petit blog personnel où je partage surtout des recettes de cuisine, quelques réflexions et  pensées de douche, et éventuellement des astuces ou des trouvailles. 

~{{<icon-group>}}{{< icon vendor = "simple" name  = "discord" link = "https://discordapp.com/users/narsyt" >}}{{< icon vendor = "feather" name = "mail" link = "mailto:blog@ckevin.fr">}}{{< icon vendor = "feather" name = "github" link = "https://github.com/chnkvn">}}{{< icon vendor = "simple" name = "buymeacoffee" link = "https://buymeacoffee.com/ckevin" >}}{{</icon-group>}}~



#+begin_comment
retirer signes verbose fichier généré 
#+end_comment
